apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: argocd
  sources:
    - repoURL: "https://github.com/unleftie/k8s-sandbox.git"
      path: "monitoring/prometheus-blackbox-exporter"
      targetRevision: main
    - repoURL: "https://github.com/unleftie/k8s-sandbox.git"
      path: "monitoring/kube-prometheus-stack"
      targetRevision: main
    - repoURL: "https://github.com/unleftie/k8s-sandbox.git"
      path: "monitoring/kube-prometheus-stack/crds"
      targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
