---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: "monitoring"
    repoURL: "https://github.com/unleftie/k8s-sandbox.git"
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
