---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: prometheus-blackbox-exporter
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  source:
    repoURL: "https://github.com/unleftie/k8s-sandbox.git"
    path: "monitoring/prometheus-blackbox-exporter"
    targetRevision: main
    helm:
      repoURL: https://prometheus-community.github.io/helm-charts
      chart: "prometheus-blackbox-exporter"
      chartVersion: "9.0.0"
      valueFiles: ["values.yml"]
