---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: prometheus-blackbox-exporter
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/unleftie/k8s-sandbox.git
      targetRevision: main
      ref: prometheus-blackbox-exporter-values
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus-blackbox-exporter
      targetRevision: 9.0.0
      helm:
        valueFiles:
          - $prometheus-blackbox-exporter-values/monitoring/prometheus-blackbox-exporter/values.yml
