---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: docker-gs-ping
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/unleftie/k8s-sandbox.git
      targetRevision: main
      ref: docker-gs-ping-values
    - repoURL: https://unleftie.github.io/docker-gs-ping
      chart: docker-gs-ping
      targetRevision: 1.3.4
      helm:
        valueFiles:
          - $docker-gs-ping-values/services/docker-gs-ping/values.yml
