---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx-monitoring-crd
  namespace: monitoring
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: kube-prometheus-stack-grafana
                port:
                  number: 80
