# k apply -f prometheus-external-alerting-rules-crd.yml
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-external-alerting-rules-crd
  namespace: monitoring
  labels:
    env: dev
    helmStack: prometheus
spec:
  groups:
    - name: blackbox_icmp
      rules:
        - alert: EndpointDown
          expr: "probe_success{job='blackbox_icmp'} == 0"
          for: 2m
          labels:
            severity: critical
          annotations:
            description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 2 minutes"
            summary: "ICMP request failure"
    - name: blackbox_http
      rules:
        - alert: EndpointDown
          expr: "probe_success{job='blackbox_http'} == 0"
          for: 2m
          labels:
            severity: critical
          annotations:
            description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 2 minutes"
            summary: "HTTP request failure"
