---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: ingress-nginx-monitoring
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/unleftie/k8s-sandbox.git
      targetRevision: main
      ref: ingress-nginx-values
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.11.2
      helm:
        valueFiles:
          - $ingress-nginx-values/networking/ingress-nginx/values.yml
